### ISSUE TITLE
Organize ProblemStatement and Problem Category views

### ISSUE THREAD

**Issue by shashank-sharma** [isohack/hackathon-webapp#51]
In PR: https://github.com/isohack/hackathon-webapp/pull/50

I think there should be separate class API views for statement and category and can be fixed in future

**Comment by borsezf2** [comment]
on it,

**Comment by shashank-sharma** [comment]
@borsezf2 Just to help
Have a look at: https://github.com/isohack/hackathon-webapp/blob/master/account/api/views.py#L13

You need:
1. Serializers
2. Permission classes, it can be empty for now or you can pass on any permission class

More: To filter based on id you can do something like this
https://www.django-rest-framework.org/api-guide/filtering/#filtering-against-the-current-user

Here user id can be problem category id and purchase model can be problem statement model which is filtered by id
